### PR TITLE
add documentation and write file extension in download.py

### PR DESCRIPTION
**Pull request by clhenrick**
After dl'ing a file use python-magic to identify file type then write either the .html or .pdf extension.

### CODE REVIEW

**Comment by talos** [comment]
@clhenrick This is cool.  Thank you so much for putting together a README!

I have some reservations about requiring people install stuff at the system level (libmagic) for file type identification.  It makes the code much less portable, as `brew install` doesn't carry over to other OS's (while `pip install` is OK.)

Because NYCServ provides proper response headers for PDF vs. HTML, we can actually just use the `requests` library's very nice response object to figure out what the file extension could be without mucking around with extra modules at all.

**Inferring PDF filetype from response headers**

```
import requests
pdf_url = "http://nycprop.nyc.gov/nycproperty/StatementSearch?bbl=3017720074&stmtDate=20140822&stmtType=SOA"
response = requests.get(pdf_url, stream=True)
print response.headers["Content-Type"]
## Should print "application/pdf"
```

**Inferring HTML filetype from response headers**

```
import requests
html_url = "http://nycprop.nyc.gov/nycproperty/statements/mvh/jsp/stmtassessmvh.jsp?statementId=163923398"
response = requests.get(html_url, stream=True)
print response.headers["Content-Type"]
## Should print "text/html;charset=ISO-8859-1"
```

Would you be OK with stripping out the `brew install` & content sniffing to do this, and simply using the headers they provide?

**Comment by clhenrick** [comment]
done!

**Comment by clhenrick** [comment]
ah yeah, I'm no python expert so it was my best effort!

**Comment by talos** [comment]
@clhenrick This is really close, but I think there's some additional refactoring I'd like to do before merging this in.  I'll probably pull down your branch, make those changes, then merge it into master.  I probably won't get a chance to do this til tomorrow at the earlier.

Thanks again!

**Pull request merged**
