### PR TITLE
notice of property values PDFs

### PR DESCRIPTION
**Pull request by romeboards**
created separate **property-value** folder containing a JS scraper for _Notice of Property Value_ PDFs. returns **estimated gross income** for years 2010-2015 and **estimated expenses** for 2011-2015 thus far

### CODE REVIEW

**Comment by talos** [comment]
@romeboards Reviewing this now.  It looks like some output data crept in there, which I'm going to remove.

**Comment by talos** [comment]
@romeboards Awesome work!  I've made a buncha changes and merged into master.  Primarily:
- Eliminated example files and scripts, replaced with README
- Outputs CSV instead of JSON now
- Synchronized across multiple files, so a single call to `scrape.js` can handle multiple glob'd shell arguments (for example, `node scrape.js /path/to/files/*.pdf`.)
- Generally just cleaned and reorganized the script.  It was good before, I think it's better now. :)

A few things I'd love to see, that aren't in there yet:
- Date of the NoPV
- BBL and/or address of the NoPV (this could also be read in from the filepath, by convention, but this isn't done right now.)

If you have an interest in doing those, please let me know.  If you have any words of warning, please warn me, so I'll know what to watch out for!

Thanks again, and good stuff.

**Comment by romeboards** [comment]
Looks good! Changes make sense for eventually integrating all that data together amongst different documents. Date shouldn't be too hard - had that in a previous version. BBL might be a little harder, I'll see what I can do.

**Comment by talos** [comment]
@romeboards Hmm, thinking about it more actually I don't think either (dates or BBLs) are strictly necessary.

Taking a look at how output is saved from the scraper at http://104.236.234.7/, the BBL can just be pulled out of the directory name, and the date can be pulled out of the document title (for example, http://104.236.234.7/1-01412-0028/January%2015%2c%202010%20-%20Notice%20of%20Property%20Value.pdf ).

If you wanted, it'd be cool to update the scraper to pull those out of the path/filename, as opposed to from within the doc.  I can also do it if you're not sure of the best approach -- I would recommend pulling down some files from that site and replicating the directory structure locally.

In terms of scraping, what would be really neat is actually to pull out the mailing address from the NoPV.  For example, in the above it's

> LRC-167 EST 77TH STRE
> 20 VESEY ST
> NEW YORK NY 10007-2913 

Those mailing addresses are actually quite interesting, as I'm not sure how they line up with the official owner's address.

**Comment by talos** [comment]
And thank you again for the awesome work. :+1:

**Comment by talos** [comment]
@romeboards I got BBL and date in there with 254543c3ff336ed748aa107296dfd4e180415f72. If you want to do address, that'd be awesome.  Otherwise, if you've got bandwidth, it would be awesome if you could take a stab at the HTML NoPVs...

**Pull request merged**
